version: '3.1'

services:

  sut:
    build:
      context: .
    command: /run_tests.sh
    env_file: .env
    depends_on:
      - assets
    volumes:
      - jhuda-assets:/data

  assets:
    image: jhuda/assets:latest
    volumes:
      - jhuda-assets:/data

volumes:

  jhuda-assets:
    driver: local