version: '3.1'

services:

  fcrepo:
    build:
      context: .
    image: jhuda/fcrepo:latest
    container_name: fcrepo
    env_file: .env
    ports:
      - "${FCREPO_JETTY_PORT}:${FCREPO_JETTY_PORT}"
    volumes:
      - jhuda-assets:/data
    depends_on:
      - assets

  assets:
    image: jhuda/assets:latest
    container_name: assets
    volumes:
      - jhuda-assets:/data

volumes:

  jhuda-assets:
    driver: local